const baseURL = "https://api.aniapi.com/v1/oauth"
class AuthClient {
    /**
     * 
     * @param {string} client_id - Your client ID
     * @param {string} redirect_uri - Your client redirect URI 
     */
    constructor(client_id, redirect_uri) {
        this.client_id = client_id;
        this.redirect_uri = redirect_uri;
    };
    /**
     * 
     * @param {"Authorization" | "Implicit"} response_type 
     * @param {string} [state] - A random string generated by your application [**optional**]
     * @returns {Promise<string>} A complete URI to pass into your redirect function, handler, etc.
     */
    async ConstructURI(response_type, state) {
        return (response_type === "Authorization") ? `${baseURL}?response_type=token&client_id=${this.client_id}&redirect_uri=${this.redirect_uri}${(state) ? `&state=${state}`: ""}` : `${baseURL}?response_type=code&client_id=${this.client_id}&redirect_uri=${this.redirect_uri}&state=${state}`
    }
}
module.exports = {AuthClient};